---
title: "EDA & Clustering Work"
author: "Stephen Pelkofer"
date: "5/13/2020"
output: 
  github_document: default
  html_document: default
---
## Libraries & Data

```{r}
library(tidyverse)
library(caret)
library(ggthemes)
library(ggtext)
library(tidymodels)
library(tidyr)
library(Rtsne)
library(plotly)
```

```{r}
beer_data <- read_csv("../data/CleanedBeerData.csv")
```

## EDA

```{r}
numeric_beer_cols <- beer_data %>%
  select(!c("Calories_from_fat","Cholesterol_mg","Fat_grams","Saturated_fat_grams","Trans_fat_grams","Fiber_grams")) %>%
  select(!contains("Ingr")) %>%
  select(!contains("Brand")) %>%
  gather()

numeric_beer_cols %>%
  group_by(key) %>%
  summarise(mean(value),min(value),max(value))
```

View distribution of all numeric columns (not including dummy vars)

*Columns with mean == 0 should be dropped (not displayed here)

```{r}
numeric_beer_cols %>%
  ggplot(aes(value)) +
  geom_histogram(bins = 8, fill = "#2b8cbe",color = "white") +
  facet_wrap(~key, scales = "free") +
  labs(title = "Numeric Column Distributions") +
  theme_bw()
```

View distribution by brnad style - in the clustering process, this could be a way to "check" your answers

```{r}
beer_data %>%
  group_by(Brand_Style) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(n = 10) %>%
  ggplot(aes(x = reorder(Brand_Style,count),y = count)) +
  geom_bar(stat = "identity", fill = "#2b8cbe",color = "white") +
  coord_flip() +
  labs(title = "Top 10 Most Common Brand Styles") +
  theme_minimal() +
  theme(axis.title.y = element_blank())
```


## PCA of Numeric Columns

```{r}
beer_data_numeric <- beer_data %>%
  select(!c("Calories_from_fat","Cholesterol_mg","Fat_grams","Saturated_fat_grams","Trans_fat_grams","Fiber_grams")) %>%
  select(!contains("Ingr")) %>%
  select(!contains("Brand"))
```


```{r}
pca <- princomp(beer_data_numeric, cor = TRUE, scores = TRUE)
PCs <- as.data.frame(pca$scores[,1:2])
PC_plotting_data <- cbind(PCs,beer_data)
ggplot(data = PC_plotting_data) +
  geom_point(aes(x = Comp.1, y = Comp.2, alpha = ABV),
             color = "#2b8cbe",
             size = 2) +
  labs(title = "First Two PCs of Beer Data",
       subtitle = "Numeric columns only") +
  theme(plot.title = element_markdown(size = 14),
        plot.subtitle = element_markdown(size = 10),
        plot.caption = element_markdown(),
        legend.position = "top",
        panel.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_line(colour = "gray",size = .1))

```


## t-SNE Implementation

```{r}
beer_all_features <- beer_data %>% select(!c("Brand","Brand_Style","Ingredients"))
```


```{r}
## Algo
tsne <- Rtsne(beer_all_features,
              check_duplicates = FALSE,
              dims = 2,
              perplexity=50,
              verbose=TRUE,
              max_iter = 1000)

# Plotting t-SNE
tsne_plotting_data <- cbind(beer_data %>% select("Brand","Brand_Style","ABV","Calories"),tsne$Y)
gg_tsne <- ggplot(data = tsne_plotting_data) +
  geom_point(aes(x = `1`, y = `2`, text = paste("Beer:",Brand,"<br>","Style:",Brand_Style)),
             color = "#2b8cbe",
             size = 2,
             alpha = .7) +
  labs(title = "tSNE 2-D Respresentation of Beer Data") +
  theme(plot.title = element_markdown(size = 14),
        plot.subtitle = element_markdown(size = 10),
        plot.caption = element_markdown(),
        legend.position = "top",
        panel.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_line(colour = "#f0f0f0",size = .1))

ggplotly(gg_tsne, tooltip = "text") %>%
            config(displayModeBar = F)
```

## K-Means Implementation
Resource: https://www.tidymodels.org/learn/statistics/k-means/

```{r}
PCs <- as.data.frame(pca$scores)

kclusts <- 
  tibble(k = 1:15) %>%
  mutate(
    kclust = map(k, ~kmeans(PCs, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, PCs)
  )

clusters <- 
  kclusts %>%
  unnest(cols = c(tidied))

assignments <- 
  kclusts %>% 
  unnest(cols = c(augmented))

clusterings <- 
  kclusts %>%
  unnest(cols = c(glanced))
```


```{r}
p1 <- 
  ggplot(assignments, aes(x = Comp.1, y = Comp.2)) +
  geom_point(aes(color = .cluster), alpha = 0.6) + 
  facet_wrap(~ k)
p1
```

```{r}
ggplot(clusterings, aes(k, tot.withinss)) +
  geom_line() +
  geom_point()
```





























