---
title: "Beer Data EDA & Clustering"
output:
  html_notebook: default
  github_document: default
---

## Libraries & Data

```{r}
library(tidyverse)
library(caret)
library(ggthemes)
library(ggtext)
library(h2o)
h2o.no_progress()  # turn off progress bars for brevity
h2o.init()
```

```{r}
beer_data <- read_csv("../data/CleanedBeerData.csv")
```

## EDA

```{r}
numeric_beer_cols <- beer_data %>%
  select(!c("Calories_from_fat","Cholesterol_mg","Fat_grams","Saturated_fat_grams","Trans_fat_grams")) %>%
  select(!contains("Ingr")) %>%
  select(!contains("Brand")) %>%
  gather()

numeric_beer_cols %>%
  group_by(key) %>%
  summarise(mean(value),min(value),max(value))
```

View distribution of all numeric columns (not including dummy vars)

*Columns with mean == 0 should be dropped (not displayed here)

```{r}
numeric_beer_cols %>%
  ggplot(aes(value)) +
  geom_histogram(bins = 8, fill = "#2b8cbe",color = "white") +
  facet_wrap(~key, scales = "free") +
  labs(title = "Numeric Column Distributions") +
  theme_bw()
```

View distribution by brnad style - in the clustering process, this could be a way to "check" your answers

```{r}
beer_data %>%
  group_by(Brand_Style) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(n = 10) %>%
  ggplot(aes(x = reorder(Brand_Style,count),y = count)) +
  geom_bar(stat = "identity", fill = "#2b8cbe",color = "white") +
  coord_flip() +
  labs(title = "Top 10 Most Common Brand Styles") +
  theme_minimal() +
  theme(axis.title.y = element_blank())
```


## PCA of Numeric Columns

```{r}
beer_data_numeric <- beer_data %>%
  select(!c("Calories_from_fat","Cholesterol_mg","Fat_grams","Saturated_fat_grams","Trans_fat_grams")) %>%
  select(!contains("Ingr")) %>%
  select(!contains("Brand"))

h2o_beer_numeric_cols <- as.h2o(beer_data_numeric) # creste h2o object

pca_limited <- h2o.prcomp(
  training_frame = h2o_beer_numeric_cols,
  pca_method = "GramSVD",
  k = ncol(h2o_beer_numeric_cols), 
  transform = "STANDARDIZE", 
  impute_missing = TRUE,
  max_runtime_secs = 100
)
```


```{r}
pca_limited
```

```{r}
pca_limited@model$eigenvectors %>% 
  as.data.frame() %>% 
  mutate(feature = row.names(.)) %>%
  ggplot(aes(pc1, reorder(feature, pc1))) +
  geom_point() +
  labs(title = "PC1 Loadings") +
  theme_minimal() +
  theme(axis.title.y = element_blank())
```

```{r}
pca_limited@model$eigenvectors %>% 
  as.data.frame() %>% 
  mutate(feature = row.names(.)) %>%
  ggplot(aes(pc1, pc2, label = feature)) +
  geom_text()+
  labs(title = "PC1 vs PC2 Loadings") +
  theme_minimal() +
  theme(axis.title.y = element_blank())
```








