---
title: "Beer Recommender System"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(caret)
library(ggthemes)
library(ggtext)
library(tidymodels)
library(tidyr)
library(Rtsne)
library(plotly)
library(StatMatch)
library(cluster)
library(uwot)
```

## Data

```{r echo=FALSE}
beer_data <- read_csv("data/CleanedBeerData.csv")
```

## Data Processing Steps

- Remove numeric variables with zero/low variance

```{r}
beer_full <- beer_data %>%
  select(!c("Calories_from_fat","Cholesterol_mg","Fat_grams","Saturated_fat_grams","Trans_fat_grams","Fiber_grams"))
```

- Run clustering on the ingredients features (use gower distance)

## Partitioning around Medoids

```{r}
beer_ingredients <- beer_full %>% select(contains("ingr_"))
beer_ingr_gower <- dist(beer_ingredients, method = "gower")
```

```{r}
# Gower Dist - Partioning Around Medoids
cluster_data_input <- beer_full %>% select(!c("Brand","Brand_Style","Ingredients"))
cluster_dist_input <- dist(cluster_data_input, method = "gower")
avg_width = c()
for (i in 1:26) {
  pam_gower <- pam(x = cluster_dist_input, k = i, diss = TRUE)
  avg_width =  c(avg_width,pam_gower[["silinfo"]][["avg.width"]]) # append avg width for each k
}

ggplot() +
  geom_line(aes(x = c(1:25), y= avg_width)) +
  geom_point() +
  labs(title = "K vs Avg Width",
       x = "Clusters",
       y = "Avg Width") +
  theme_minimal()
```


```{r}
pam_gower <- pam(x = cluster_dist_input, k = 10, diss = TRUE, cluster.only = TRUE)
beer_data_with_clusters <- beer_full %>%
  mutate(Ingr_Cluster = as.factor(pam_gower))
```


## UMAP

- Parameters: https://rdrr.io/cran/uwot/man/umap.html


```{r}
## Algo
umap_data_input <- beer_data_with_clusters %>% 
  select(!contains("Brand")) %>%
  select(!Ingredients)

umap_output <- uwot::umap(umap_data_input,
                          y = umap_data_input$Ingr_Cluster,
                          target_weight = .5,
                          metric = "euclidean",
                          n_neighbors = 6,
                          n_components = 2,
                          spread = .75,
                          min_dist = .01,
                          scale = TRUE,
                          ret_nn = TRUE) #retain the nearest neighbors

# Plotting UMAP
umap_plotting_data <- cbind(beer_data_with_clusters,umap_output$embedding)
gg_umap <- ggplot(data = umap_plotting_data,aes(x = `1`,
                                                y = `2`,
                                                colour = Ingr_Cluster,
                                                text = paste0(Brand,"<br>",Brand_Style,"<br>","ABV: ",ABV))) +
  geom_point(colour = "#fe9929",
             alpha = .6) +
  labs(title = "UMAP 2-D Respresentation of Beer Data") +
  theme(plot.title = element_markdown(size = 14),
        plot.subtitle = element_markdown(size = 10),
        plot.caption = element_markdown(),
        legend.position = "top",
        panel.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_line(colour = "#f0f0f0",size = .1)) + 
  geom_jitter(width = 1.5, height = 1.5,alpha = .6)

ggplotly(gg_umap, tooltip = "text") %>%
            config(displayModeBar = F)
```


```{r}
# Extract Nearest Neigbor Data
beer_nn_data <- cbind(beer_data %>% select("Brand","Brand_Style"),umap_output$nn)

beer_nn_data <- beer_nn_data %>%
  pivot_longer(starts_with("euclidean"),
               names_to = c(".value", "set"),
               names_pattern = "(euclidean\\.[a-z]*\\.)(.)")
  
names(beer_nn_data) <- c("Brand","Brand_Style","Neighbor_Rk","Neighbor_Idx","Neighbor_Dist")
```



